### PR TITLE
fix(iroh-net): Make a single direct address in NodeAddr instant

### LINKED ISSUE #2546: NodeAddr with a direct address incurs an extra RTT
In #2509 we added an extra DISCO Ping-Pong exchange before we start using a direct address in all situations.  The reasoning was that this was a niche usecase which would not impact many real-life scenarios.

However it makes an iroh Endpoint no longer as good as a direct socket or QUIC endpoint.  If we have been given exactly one direct address we should start using it as well as using the relay path like before.  Otherwise we are significantly worse than a normal QUIC endpoint for this scenario and we do not want that.

If we do this, we may as well revert the entire decision and do the stable select again if there are multiple.  It seems a bit odd to now special-case this to just one direct address.

### PR DESCRIPTION
**Pull request by flub**
## Description

In #2509 (c1c3539c0a07d8659979ffacdb5bd1fc23d6939c) we removed chosing
a random unconfirmed direct address and through both it and the relay
if we did not yet have any confirmed direct address.  This required
any direct address passed in via a NodeAddr to do a DISCO Ping-Pong
round trip before it would be used.

It turns out this is used a lot in the sense that a common socket
address is used: when you know an IP is reachable.  Requiring a ping
would mean the first QUIC packets would be dropped, Quinn would wait
to detect this before retrying and connections are delayed by an
observable second by the end of it all.  Not great for this scenario,
even if it can be argued that outside of tests this is not a common
scenario.

So this brings back the random selection of unconfirmed addresses.

It tries to do this without adding more complexity to the NodeState.
Instead it consolidates the path information and best address into the
NodeUdpState struct.  But **without any logic changes.**  It then adds
just this extra caching of the chosen address to this struct.

This is a huge simplification of a much larger refactor I was trying
to do first.  I believe that was the right track but resulted in too
many changes to do in one large PR.  So the long-term goal here is to
continue removing state manipulation outside of NodeUdpState struct so
that it gains more control of how to manage the UDP paths.  This will
help the logic of how UDP paths are chosen to be based entirely on the
PathState - which is the right model for this.

## Breaking Changes

None

## Notes & open questions

Fixed #2546

## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
doc comments are sad

File: iroh-net/src/magicsock/node_map/node_state.rs [hunk 1]
```diff
@@ -261,31 +261,34 @@ impl NodeState {
...
             debug!("in `DEV_relay_ONLY` mode, giving the relay address as the only viable address for this endpoint");
             return (None, self.relay_url());
         }
-        // Update our best addr from candidate addresses (only if it is empty and if we have
-        // recent pongs).
-        self.assign_best_addr_from_candidates_if_empty();
-        let (best_addr, relay_url) = match self.best_addr.state(*now) {
-            best_addr::State::Valid(best_addr) => {
+        let (best_addr, relay_url) = match self.udp_paths.send_addr(*now, have_ipv6) {
+            super::udp_paths::UdpSendAddr::Valid(addr) => {
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/node_state.rs:274]: probably nicer if you import this

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+use tracing::warn;
+
+use crate::disco::SendAddr;
+
+use super::best_addr::{self, BestAddr};
+use super::node_state::{PathState, PongReply};
+use super::IpPort;
+
+#[derive(Debug)]
+pub(super) enum UdpSendAddr {
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:21]: would be good to have some docs on this enum

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+    /// it should be `&self` and not `&mut self`.  This is only possible once the state from
+    /// [`NodeUdpPaths`] is no longer modified from outside.
+    pub(super) fn send_addr(&mut self, now: Instant, have_ipv6: bool) -> UdpSendAddr {
+        self.assign_best_addr_from_candidates_if_empty();
+        match self.best_addr.state(now) {
+            best_addr::State::Valid(addr) => UdpSendAddr::Valid(addr.addr),
+            best_addr::State::Outdated(addr) => UdpSendAddr::Outdated(addr.addr),
+            best_addr::State::Empty => {
+                // No direct connection has been used before.  If we know of any possible
+                // candidate addresses, randomlly try to use one.  This path is most
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:75]: typo

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+                        // Look for a new candidate in all the known paths.  This may look
+                        // like a RNG use on the hot-path but this is normally invoked at
+                        // most most once at startup.
+                        let addr = self
+                            .paths
+                            .values()
+                            .filter_map(|path| path.udp_addr())
+                            .filter(|addr| addr.is_ipv4() || have_ipv6)
+                            .choose(&mut rand::thread_rng());
+                        self.chosen_candidate = addr.as_ref().map(|addr| IpPort::from(*addr));
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:94]: I think `addr.map(IpPort::from)`  should work

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+                    });
+                match addr {
+                    Some(addr) => UdpSendAddr::Unconfirmed(addr),
+                    None => UdpSendAddr::None,
+                }
+            }
+        }
+    }
+
+    /// Fixup best_adrr from candidates.
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:105]: typo

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+    ///
+    /// If somehow we end up in a state where we failed to set a best_addr, while we do have
+    /// valid candidates, this will chose a candidate and set best_addr again.  Most likely
+    /// this is a bug elsewhere though.
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:109]: if this is a bug, shouldn't we log that we are doing this, to figure out why this happens?

File: iroh-net/src/magicsock/node_map/udp_paths.rs [hunk 7]
```diff
@@ -0,0 +1,148 @@
...
+    fn assign_best_addr_from_candidates_if_empty(&mut self) {
+        if !self.best_addr.is_empty() {
+            return;
+        }
+
+        // The highest acceptable latency for an endpoint path.  If the latency is higher
+        // then this the path will be ignored.
+        const MAX_LATENCY: Duration = Duration::from_secs(60 * 60);
```
Comment (dignifiedquire) [inline iroh-net/src/magicsock/node_map/udp_paths.rs:117]: this seems rather pointless.. latency of 1 hour?

File: iroh-net/src/magicsock/node_map/udp_paths.rs (hunk 6 above)
Comment (flub) [reply iroh-net/src/magicsock/node_map/udp_paths.rs:109]: It is already logged on `warn` for this purpose.

File: iroh-net/src/magicsock/node_map/udp_paths.rs (hunk 7 above)
Comment (flub) [reply iroh-net/src/magicsock/node_map/udp_paths.rs:117]: Yes, I don't really know how this is useful either.  Though this code is copy-pasted and I'd really like to avoid doing unrelated changes here.  I do want to carry on fixing up things here though, but in small PRs that each target one thing because my attempt to do a bunch of this together became messy and un-reviewable.

**Comment by flub** [comment]
fwiw test that rely on this functionality now run in 200ms again instead of being 1.2s

**Review by dignifiedquire — APPROVED** [review]
