### PR TITLE
fix(iroh-store): `put_many` bug

### LINKED ISSUE #423: Intermittent add/get roundtrip failure with real store
Branch for investigation: https://github.com/n0-computer/iroh/tree/rklaehn/get-bug-investigatin

### PR DESCRIPTION
**Pull request by ramfox**
closes #423

### CODE REVIEW

File: iroh-store/src/store.rs [hunk 1]
```diff
@@ -366,11 +367,14 @@ impl<'a> WriteStore<'a> {
         let mut total_blob_size = 0;
 
         let mut batch = WriteBatch::default();
+        let mut cid_tracker: HashSet<Cid> = std::collections::HashSet::default();
         for (cid, blob, links) in blocks.into_iter() {
-            if self.has(&cid)? {
-                return Ok(());
+            if self.has(&cid)? || cid_tracker.contains(&cid) {
+                continue;
```
Comment (rklaehn) [inline iroh-store/src/store.rs:373]: Yes, obvious in retrospect, like so many bugs...

File: iroh-store/src/store.rs [hunk 2]
```diff
@@ -366,11 +367,14 @@ impl<'a> WriteStore<'a> {
         let mut total_blob_size = 0;
 
         let mut batch = WriteBatch::default();
+        let mut cid_tracker: HashSet<Cid> = std::collections::HashSet::default();
```
Comment (rklaehn) [inline iroh-store/src/store.rs:370]: I would use an AHashSet ( https://docs.rs/ahash/latest/ahash/ ) since it is faster.

Dig is quite fond of it, and it is already in our dependencies anyway.

File: iroh-store/src/store.rs [hunk 3]
```diff
@@ -366,11 +367,14 @@ impl<'a> WriteStore<'a> {
...
         for (cid, blob, links) in blocks.into_iter() {
-            if self.has(&cid)? {
-                return Ok(());
+            if self.has(&cid)? || cid_tracker.contains(&cid) {
```
Comment (rklaehn) [inline iroh-store/src/store.rs:372]: Not that it matters that much, but do the cid_tracker membership test first. It is much faster than having to go all the way to the DB.

File: iroh-store/src/store.rs [hunk 4]
```diff
@@ -911,4 +915,32 @@ mod tests {
         assert_eq!(Vec::<String>::new(), store.consistency_check()?);
         Ok(())
     }
+
+    #[tokio::test]
+    async fn test_put_many_repeat_ids() -> anyhow::Result<()> {
```
Comment (rklaehn) [inline iroh-store/src/store.rs:920]: :+1:

**Review by rklaehn — APPROVED** [review]
See the comments for some minor improvements

File: iroh-store/src/store.rs (hunk 3 above)
Comment (ramfox) [reply iroh-store/src/store.rs:372]: love these little pieces of advice!

File: iroh-store/src/store.rs (hunk 2 above)
Comment (ramfox) [reply iroh-store/src/store.rs:370]: 🔥

File: iroh-store/src/store.rs [hunk 5]
```diff
@@ -367,9 +367,9 @@ impl<'a> WriteStore<'a> {
         let mut total_blob_size = 0;
 
         let mut batch = WriteBatch::default();
-        let mut cid_tracker: HashSet<Cid> = std::collections::HashSet::default();
+        let mut cid_tracker: AHashSet<Cid> = AHashSet::default();
```
Comment (rklaehn) [inline iroh-store/src/store.rs:370]: If we had a vec we could use https://docs.rs/ahash/latest/ahash/struct.AHashSet.html#method.with_capacity here to make sure the hashset does not need to rehash.

But with the iterator we could just use the size hint, which is probably not worth it.

**Review by rklaehn — APPROVED** [review]

File: iroh-store/src/store.rs (hunk 5 above)
Comment (dignifiedquire) [reply iroh-store/src/store.rs:370]: `HashSet`s have `with_capacity`: https://docs.rs/ahash/latest/ahash/struct.AHashSet.html#method.with_capacity
