### PR TITLE
ref(lru-cache): Change lru cache crate to avoid vulnerable dependency

### LINKED ISSUE #375: Fix cargo audit errors
Is this ticket stale? The `cargo-audit` invocation itself works fine but we're currently failing audit due to two dependencies:

```
$ git rev-parse HEAD
5114380c98045067e5ffeb6875b280a0095bcc2b
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 462 security advisories (from /home/jmcph4/.cargo/advisory-db)
    Updating crates.io index
    Updating git repository `https://github.com/dignifiedquire/rust-libp2p`
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (613 crate dependencies)
Crate:     time
Version:   0.1.43
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.43
└── chrono 0.4.22
    ├── serde_with 2.0.1
    │   └── iroh-rpc-types 0.1.0
    │       ├── iroh-store 0.1.0
    │       │   ├── iroh-share 0.1.0
    │       │   ├── iroh-resolver 0.1.0
    │       │   │   ├── iroh-share 0.1.0
    │       │   │   ├── iroh-one 0.1.0
    │       │   │   ├── iroh-gateway 0.1.0
    │       │   │   │   └── iroh-one 0.1.0
    │       │   │   ├── iroh-examples 0.1.0
    │       │   │   └── iroh-api 0.1.0
    │       │   │       └── iroh 0.1.0
    │       │   │           ├── xtask 0.1.0
    │       │   │           └── iroh 0.1.0
    │       │   ├── iroh-one 0.1.0
    │       │   └── iroh-gateway 0.1.0
    │       ├── iroh-share 0.1.0
    │       ├── iroh-rpc-client 0.1.0
    │       │   ├── iroh-store 0.1.0
    │       │   ├── iroh-share 0.1.0
    │       │   ├── iroh-resolver 0.1.0
    │       │   ├── iroh-p2p 0.1.0
    │       │   │   ├── iroh-share 0.1.0
    │       │   │   └── iroh-one 0.1.0
    │       │   ├── iroh-one 0.1.0
    │       │   ├── iroh-gateway 0.1.0
    │       │   ├── iroh-examples 0.1.0
    │       │   └── iroh-api 0.1.0
    │       ├── iroh-resolver 0.1.0
    │       ├── iroh-p2p 0.1.0
    │       ├── iroh-one 0.1.0
    │       ├── iroh-gateway 0.1.0
    │       └── iroh-api 0.1.0
    └── caches 0.2.2
        ├── iroh-p2p 0.1.0
        └── iroh-bitswap 0.1.0
            └── iroh-p2p 0.1.0

Crate:     tempdir
Version:   0.3.7
Warning:   unmaintained
Title:     `tempdir` crate has been deprecated; use `tempfile` instead
Date:      2018-02-13
ID:        RUSTSEC-2018-0017
URL:       https://rustsec.org/advisories/RUSTSEC-2018-0017
Dependency tree:
tempdir 0.3.7
├── iroh-one 0.1.0
└── iroh-api 0.1.0
    └── iroh 0.1.0
        ├── xtask 0.1.0
        └── iroh 0.1.0

error: 1 vulnerability found!
warning: 1 allowed warning found
```

The `chrono` one is [notorious](https://github.com/chronotope/chrono/issues/602#issuecomment-1242149249) and is definitely solved. As for `tempdir`, the advisory seems pretty clear to use [`tempfile`](https://crates.io/crates/tempfile) instead now.

At the moment, our use of `tempdir` seems both pretty straightforward and only in tests, which bodes well for the simplicity of a potential patch:

https://github.com/n0-computer/iroh/blob/5114380c98045067e5ffeb6875b280a0095bcc2b/iroh-api/src/api_ext.rs#L112

I guess this ticket is resolved by:

 - Fixing the upstream offenders
   - Fix `chrono` by using the correct feature guards
   - Use `tempfile` over `tempdir` in tests 
 - Add `cargo-audit` invocation to CI

_Originally posted by @jmcph4 in https://github.com/n0-computer/iroh/issues/8#issuecomment-1283415098_

### PR DESCRIPTION
**Pull request by flub**
Change the LRU cache from the caches crate to the lru crate.  This crate is much simpler and does not depend on a vulnerable version of the time crate, resolving our cargo-audit issues.

A benchmark is included showing our use of the LRU cache to have no notable performance difference between both crates.

Closes #375

### CODE REVIEW

File: iroh-p2p/benches/lru_cache.rs [hunk 1]
```diff
@@ -0,0 +1,316 @@
...
+//! Run the benchmarks:
+//!
+//! ```shell
+//! cargo criterion -p iroh-p2p
+//! ```
+//!
+//! # Disabled benches
+//!
+//! The bench functions for the `caches` crate are commented out in order not to require a
+//! dependency on the crate.
```
Comment (b5) [inline iroh-p2p/benches/lru_cache.rs:23]: Let's remove these entirely, and reposition this PR as swapping out the `caches` crate for `lru`, but also comes with the upside of having a benchmark

File: iroh-p2p/benches/lru_cache.rs [hunk 2]
```diff
@@ -0,0 +1,316 @@
...
+//!
+//! ```shell
+//! cargo install cargo-criterion
+//! ```
+//!
+//! Run the benchmarks:
+//!
+//! ```shell
+//! cargo criterion -p iroh-p2p
+//! ```
```
Comment (b5) [inline iroh-p2p/benches/lru_cache.rs:18]: ran these locally, works! If we add more benchmarks that use this pattern we can define an `xtask` to run them. I'd skip it for this one, as we're mainly hanging on to this bench for future use

**Review by b5 — COMMENTED** [review]
I vote we remove the commented out caches bench entirely, then this is good-to-go

**Review by rklaehn — APPROVED** [review]
With the removal of the old cache bench, works for me!

**Review by rklaehn — APPROVED** [review]

File: iroh-p2p/benches/lru_cache.rs (hunk 2 above)
Comment (dignifiedquire) [reply iroh-p2p/benches/lru_cache.rs:18]: I am confused, you can just run the benchmarks with `cargo bench` if the config is setup correctly: https://github.com/bheisler/criterion.rs#quickstart

File: iroh-p2p/benches/lru_cache.rs [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+
+use criterion::{criterion_group, criterion_main, BatchSize, Criterion};
+use libp2p::PeerId;
+
+// The size of the cache to make.  Taken from behaviour::peer_manager::DEFAULT_BAD_PEER_CAP.
```
Comment (dignifiedquire) [inline iroh-p2p/benches/lru_cache.rs:23]: should be `///`

File: iroh-p2p/benches/lru_cache.rs (hunk 2 above)
Comment (flub) [reply iroh-p2p/benches/lru_cache.rs:18]: true, i forgot that worked by the time i was finished: https://github.com/n0-computer/iroh/pull/483
