### PR TITLE
fix(iroh): do not exit on ctrl+c

### LINKED ISSUE #1690: use `EOF` (ctrl+d) to exit console instead of `SIGINT` (ctrl+c)
would anyone be able to ship me a PR that makes ctrl+D the way to exit the console instead of ctrl+C? (technically using EOF as the console kill signal instead of SIGINT)
I constantly leave my cozy home in the console by accidentally hitting ctrl+c & it kills my demo vibe.

this is the approach the python REPL uses & I love it:
```
$ python3
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
KeyboardInterrupt
>>> ^D
```
ctrl+c gives you some sort of feedback so you don't loose your mind, in this case `KeyboardInterrupt`.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #1690

### CODE REVIEW

File: iroh/src/commands/repl.rs [hunk 1]
```diff
@@ -65,8 +65,8 @@ impl Repl {
                         Some(ReplCmd::Rpc(cmd)) => self.cmd_tx.blocking_send((cmd, reply_tx))?,
                     }
                 }
-                Err(ReadlineError::Interrupted | ReadlineError::Eof) => break,
-                Err(ReadlineError::WindowResized) => continue,
+                Err(ReadlineError::Eof) => break,
+                Err(ReadlineError::Interrupted | ReadlineError::WindowResized) => continue,
```
Comment (b5) [inline iroh/src/commands/repl.rs:69]:
```suggestion
                Err(ReadlineError::Interrupted) => {
                    println!("KeyboardInterrupt (press Ctrl-D to exit)");
                    continue;
                }
                Err(ReadlineError::WindowResized) => continue,
```

**Review by b5 — APPROVED** [review]
