### PR TITLE
fix(iroh)!: don't stop address lookup when one service errors

### LINKED ISSUE #4125: bug: `AddressLookup::resolve()` cuts stream prematurely on item resolution error
**Describe the bug**
[`AddressLookup::resolve()`](https://docs.rs/iroh/latest/iroh/address_lookup/trait.AddressLookup.html#method.resolve) returns a `BoxStream<Result<Item, _>>`, but currently if a resolver returns any `Err(_)` in the stream, the remainder of the stream will cease ([replacing the merged resolver stream with `n0_future::stream::pending()`](https://github.com/n0-computer/iroh/blob/main/iroh/src/socket/remote_map/remote_state.rs#L602-L632)).

**Relevant Context**
This was discovered on a phone not connected to internet/wifi, but with [`iroh-ble-transport`](https://github.com/mcginty/iroh-ble-transport) enabled along with its resolver.

The logs would show a DNS resolver error, and then my BLE resolutions would mysteriously not arrive.

**Expected behavior**
The stream should produce a `Err(_)` but let the consumer decide what to do with that, while allowing other resolutions to arrive with `Ok(item)` after the error. The consumer can close the stream as they'd like.

**Iroh**

```
iroh v0.97.0
└── iroh-gossip v0.97.0
    ├── iroh-gossip feature "default"
    │   └── iroh-ble-chat v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/demos/iroh-ble-chat/src-tauri)
    │       └── iroh-ble-chat feature "default" (command-line)
    ├── iroh-gossip feature "metrics"
    │   └── iroh-gossip feature "default" (*)
    └── iroh-gossip feature "net"
        └── iroh-gossip feature "default" (*)
├── iroh feature "default"
│   ├── iroh-ble-chat v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/demos/iroh-ble-chat/src-tauri) (*)
│   ├── iroh-ble-chat-protocol v0.1.0-alpha.5 (/Users/jakebot/git/iroh-ble-transport/demos/protocol)
│   │   └── iroh-ble-chat-protocol feature "default" (command-line)
│   │       └── iroh-ble-chat v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/demos/iroh-ble-chat/src-tauri) (*)
│   └── iroh-ble-transport v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/crates/iroh-ble-transport)
│       └── iroh-ble-transport feature "default" (command-line)
│           └── iroh-ble-chat v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/demos/iroh-ble-chat/src-tauri) (*)
├── iroh feature "fast-apple-datapath"
│   └── iroh feature "default" (*)
├── iroh feature "metrics"
│   └── iroh feature "default" (*)
├── iroh feature "portmapper"
│   └── iroh feature "default" (*)
└── iroh feature "unstable-custom-transports"
    ├── iroh-ble-chat v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/demos/iroh-ble-chat/src-tauri) (*)
    └── iroh-ble-transport v0.1.0-alpha.6 (/Users/jakebot/git/iroh-ble-transport/crates/iroh-ble-transport) (*)
```

Endpoint configuration:
```rust
    let transport: Arc<dyn iroh::endpoint::transports::CustomTransport> = ble_transport.clone();

    // BLE-tuned QUIC idle timeout. The default (30s) leaves a large window
    // between BLE-level disconnect detection (~6s via ReliableChannel's
    // LINK_DEAD_DEADLINE) and iroh finally marking the connection dead, which
    // manifests as the UI showing a peer as connected long after the BLE link
    // is gone. 15s is short enough to cut that gap noticeably while still
    // tolerating the multi-second pauses real BLE links exhibit.
    let transport_cfg = QuicTransportConfig::builder()
        .max_idle_timeout(Some(
            std::time::Duration::from_secs(15)
                .try_into()
                .expect("15s fits in IdleTimeout"),
        ))
        .build();

    let ep = Endpoint::builder(presets::N0DisableRelay)
        .add_custom_transport(Arc::clone(&transport))
        .address_lookup(lookup)
        .transport_config(transport_cfg)
        .secret_key(st.secret_key.clone())
        .clear_ip_transports()
        .bind()
        .await
        .map_err(|e| e.to_string())?;
```

**Platform(s)**
Originally discovered on a Pixel 6a (Android)

### PR DESCRIPTION
**Pull request by Frando**
## Description

We currently abort address lookup on the first error from *any* service. This is a bug, we should run each service to completion and only abort once all completed or failed.

Fixes #4125

Turns out our current errors were not equipped to handle this well. Refactored into
a) The error returned from an individual address lookup service. This is just a struct now, because `NoServicesConfigured` didn't ever make sense here, and `NoResults` is expressed by returning `None` without yielding items.
b) The error returned from a lookup across all services now has `NoServicesConfigured` and `NoResults` variants only, where the latter can contain the errors emitted from individual services

## Breaking Changes

* changed: `iroh::address_lookup::Error` is now a struct. Existing constructor methods are unchanged.
* changed: `iroh::endpoint::ConnectWithOptsError::NoAddress { source }`: The `source` field now has type `AddressLookupFailed`, which is a new error type that can hold errors for *all* failed lookup services

## Notes & open questions

It might be more appropriate to move the new format of the stream right into `ConcurrentAddressLookup`. However, with the different error type, it could no longer implement `AddressLookup` - which it arguably doesn't have to. Maybe that would be the cleaner refactor?

See #4130 

## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

File: iroh/src/address_lookup.rs [hunk 1]
```diff
@@ -290,16 +290,31 @@ impl AddressLookupBuilderError {
 #[stack_error(derive, add_meta)]
 #[non_exhaustive]
 #[derive(Clone)]
-pub enum Error {
+pub enum LookupFailed {
```
Comment (rklaehn) [inline iroh/src/address_lookup.rs]: I know it's a bikeshed, but I would also not hate this being called AddressLookupFailed

**Review by dignifiedquire — APPROVED** [review]
important fix

File: iroh/src/address_lookup.rs (hunk 1 above)
Comment (Frando) [reply iroh/src/address_lookup.rs]: changed it!
