### PR TITLE
fix(netwatch): BSD rebind socket on errors

### LINKED ISSUE #2909: BSD RouteMonitor does not handle AF_ROUTE socket disconnection well
On a few different iPhones, the AF_ROUTE socket in the `RouteMonitor` task has disconnected which resulted in [this log](https://github.com/n0-computer/iroh/blob/23b874c0d52dab340ce7fe03263d3e26e605e772/net-tools/netwatch/src/netmon/bsd.rs#L54) `AF_ROUTE: error reading: Os { code: 57, kind: NotConnected, message: \"Socket is not connected\" }` displaying every millisecond until the app was killed by the os.

I believe this always happened while the app was in the background.

I'm not sure what the significance of that socket disconnecting is, so I'm unsure whether recreating it would work or if the task should just exit at that point

### PR DESCRIPTION
**Pull request by dignifiedquire**
also uses `AbortOnDropHandle` to better cleanup tasks

Closes #2909

### CODE REVIEW

File: net-tools/netwatch/src/netmon.rs [hunk 1]
```diff
@@ -30,27 +29,27 @@ use self::actor::{Actor, ActorMessage};
 #[derive(Debug)]
 pub struct Monitor {
     /// Task handle for the monitor task.
-    handle: JoinHandle<()>,
+    #[allow(dead_code)]
+    handle: AbortOnDropHandle<()>,
```
Comment (flub) [inline net-tools/netwatch/src/netmon.rs:33]:
```suggestion
    _handle: AbortOnDropHandle<()>,
```
?

File: net-tools/netwatch/src/netmon.rs [hunk 2]
```diff
@@ -30,27 +29,27 @@ use self::actor::{Actor, ActorMessage};
...
     /// Create a new monitor.
     pub async fn new() -> Result<Self> {
         let actor = Actor::new().await?;
         let actor_tx = actor.subscribe();
 
         let handle = tokio::task::spawn(async move {
-            actor.run().await;
+            if let Err(err) = actor.run().await {
+                warn!("netmon actor died: {:?}", err);
+            }
```
Comment (flub) [inline net-tools/netwatch/src/netmon.rs:46]: This is essentially a supervisor.  The problem with this version is that you get a single WARN in the logfile and things just carry on.  I wonder if maybe it might as well restart the actor - maybe with a small delay.  That is still not proper supervision - if it keeps dying we should bring down the entire Endpoint - but it's a start and we'll flood the logs with WARN messages which could be a bit more obvious.

File: net-tools/netwatch/src/netmon/actor.rs [hunk 3]
```diff
@@ -127,10 +126,14 @@ impl Actor {
                         debounce_interval.reset_immediately();
                     }
                 }
-                Some(_event) = self.mon_receiver.recv() => {
-                    trace!("network activity detected");
-                    last_event.replace(false);
-                    debounce_interval.reset_immediately();
+                Some(event) = self.mon_receiver.recv() => {
+                    match event {
+                        NetworkMessage::Change => {
```
Comment (flub) [inline net-tools/netwatch/src/netmon/actor.rs:131]: `Some(NetworkMessage::Change) = self.mon_receiver.recv()` might be a nicer way to write this?

I also noticed that `NetworkMessage::Change` is marked with `#[allow(dead_code)]`.  This seems suspicious, can we remove that marker as well?

File: net-tools/netwatch/src/netmon/actor.rs [hunk 4]
```diff
@@ -102,7 +101,7 @@ impl Actor {
         self.actor_sender.clone()
     }
 
-    pub(super) async fn run(mut self) {
+    pub(super) async fn run(mut self) -> Result<()> {
```
Comment (flub) [inline net-tools/netwatch/src/netmon/actor.rs:104]: I'm confused, the signature is changed but there's not a single error return?

File: net-tools/netwatch/src/netmon/bsd.rs [hunk 5]
```diff
@@ -11,22 +12,24 @@ use crate::{interfaces::bsd::WireMessage, ip::is_link_local};
 
 #[derive(Debug)]
 pub(super) struct RouteMonitor {
-    handle: JoinHandle<()>,
+    #[allow(dead_code)]
+    handle: AbortOnDropHandle<()>,
```
Comment (flub) [inline net-tools/netwatch/src/netmon/bsd.rs:16]:
```suggestion
    _handle: AbortOnDropHandle<()>,
```
?

I'm not a fan of `#[allow(dead_code)]` as it easily stays around too long.  The `_` is much easier to keep track of as the compiler will tell you.

File: net-tools/netwatch/src/netmon/bsd.rs [hunk 6]
```diff
@@ -52,12 +55,25 @@ impl RouteMonitor {
                     }
                     Err(err) => {
                         warn!("AF_ROUTE: error reading: {:?}", err);
+                        // recreate socket, as it is likely in an invalid state
```
Comment (flub) [inline net-tools/netwatch/src/netmon/bsd.rs:58]: Does this need a small delay in case this is hot-looping?

File: net-tools/netwatch/src/netmon.rs (hunk 1 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs:33]: it's actually used, which is why I don't want to use `_handle`

File: net-tools/netwatch/src/netmon.rs (hunk 2 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs:46]: generally yes, but currently there is no error case where this happens (and it is not super easy to restart the actor currently)

File: net-tools/netwatch/src/netmon/actor.rs (hunk 3 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon/actor.rs:131]: > This seems suspicious, can we remove that marker as well?

no because this message is not used on android, and I didn't want to start adding cfgs to lint hints

Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon/actor.rs:131]: > `Some(NetworkMessage::Change) = self.mon_receiver.recv()` might be a nicer way to write this?

maybe, we usually always put the match inside, so I wrote it like that for consistency

File: net-tools/netwatch/src/netmon.rs (hunk 1 above)
Comment (flub) [reply net-tools/netwatch/src/netmon.rs:33]: then it doesn't need `#[allow(dead_code)]`?

Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs:33]: but rust is too stupid..it gets constructed and it has drop semantics.. but the compiler doesn't understand that as usage

Comment (flub) [reply net-tools/netwatch/src/netmon.rs:33]: Or are we having a philosophical disagreement on what unused means?

My interpretation is the opposite in that case, to me it is definitely not dead code.  `_thing` does not mean something is unused, `let _guard = thing();` is an entirely common pattern, this is just the same but in a struct.

File: net-tools/netwatch/src/netmon/actor.rs (hunk 4 above)
Comment (flub) [reply net-tools/netwatch/src/netmon/actor.rs:104]: yeah, let's revert as then the supervisor discussion goes away as well :)

**Review by flub — APPROVED** [review]

File: net-tools/netwatch/src/netmon.rs (hunk 1 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs:33]: you are right, will change

File: net-tools/netwatch/src/netmon/bsd.rs (hunk 5 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon/bsd.rs]: fixed

File: net-tools/netwatch/src/netmon/actor.rs (hunk 3 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon/actor.rs]: see issues with tokio::select, I cleaned this up to not use an `else`branch

File: net-tools/netwatch/src/netmon/actor.rs (hunk 4 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon/actor.rs]: done

File: net-tools/netwatch/src/netmon.rs (hunk 2 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs]: removed

File: net-tools/netwatch/src/netmon.rs (hunk 1 above)
Comment (dignifiedquire) [reply net-tools/netwatch/src/netmon.rs]: fixed
