### PR TITLE
fix(iroh-net): reconfirm best addr when receiving data on it

### LINKED ISSUE #2169: connections keep switching away from direct connection and switching back
On slower connections we noticed we keep switching connections all the time.  Even though we would expect them to stay direct.  E.g. transcript from a modified `iroh doctor`:

```
Accepted connection from fltgqbqd37gta4bvy22zknq62m5xp4rucuijng7ds7up7ixl4daq
connection type changed to: relay
connection type changed to: direct
connection type changed to: mixed
connection type changed to: direct
17.978148733s: rtt: 332.081712ms
connection type changed to: mixed
connection type changed to: direct
connection type changed to: mixed
29.551192275s: rtt: 337.195327ms
connection type changed to: direct
connection type changed to: relay
connection type changed to: direct
connection type changed to: relay
Test finished after 40.893338786s: connection lost
```

### PR DESCRIPTION
**Pull request by dignifiedquire**
When receiving data via UDP, we were not extending the validity of the current `best_addr`. This would trigger expiry of the `best_addr`, even though it was actively being used. 

This fix, extends the validity, everytime we successfully receive a UDP packet on the current `best_addr`.

Closes #2169

### CODE REVIEW

File: iroh-net/src/magicsock/node_map/best_addr.rs [hunk 1]
```diff
@@ -141,6 +143,22 @@ impl BestAddr {
         }
     }
 
+    /// Reset the expiry, if the passed in addr matches the currently used one.
+    pub fn reconfirm_if_used(&mut self, addr: SocketAddr, source: Source, confirmed_at: Instant) {
+        match self.0.as_mut() {
+            None => {
+                // Nothing to do
+                // TODO: do we want to store this regardless?
```
Comment (flub) [inline iroh-net/src/magicsock/node_map/best_addr.rs:151]: no, something else is supposed to set best-addr in that case.  at least, i think so

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
nit, the description should probably describe what this fixes and why it fixes it instead of just relying on the issue link

**Comment by dignifiedquire** [comment]
> nit, the description should probably describe what this fixes and why it fixes it instead of just relying on the issue link

added more details to the description

File: iroh-net/src/magicsock/node_map/best_addr.rs (hunk 1 above)
Comment (dignifiedquire) [reply iroh-net/src/magicsock/node_map/best_addr.rs:151]: dropped
