### PR TITLE
fixes for issues found during the 0.1.2 release

### LINKED ISSUE #447: tar and zip release doesn't build
Hey,
When i download tar or zip folder with the link  (https://github.com/n0-computer/iroh/tags) of release 0.1.0 cargo cannot build project :
I have this error message : 
```
error: git describe failed with status 128: fatal: not a git repository (or any of the parent directories): .git
 --> iroh/src/metrics.rs:7:21
  |
7 |         .with_build(git_version!().to_string())
  |                     ^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `proc_macro_call` which comes from the expansion of the macro `git_version` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by dignifiedquire**
- fix #447 which prevents crates depending on the published crates in some cases
- fix hardcoded version information in tests

### CODE REVIEW

File: iroh-bitswap/src/metrics.rs [hunk 1]
```diff
@@ -1,9 +1,15 @@
...
 
 pub fn metrics_config_with_compile_time_info(cfg: MetricsConfig) -> MetricsConfig {
     // compile time configuration
     cfg.with_service_name(env!("CARGO_PKG_NAME").to_string())
-        .with_build(git_version!().to_string())
+        .with_build(
+            git_version::git_version!(
+                prefix = "git:",
+                cargo_prefix = "cargo:",
+                fallback = "unknown version"
```
Comment (Arqu) [inline iroh-bitswap/src/metrics.rs:10]: for CLI sake I'd prefer fallback to be non space separated or just `unknown`

**Review by Arqu — APPROVED** [review]
Just that one nitpick

File: iroh-bitswap/src/metrics.rs (hunk 1 above)
Comment (dignifiedquire) [reply iroh-bitswap/src/metrics.rs]: fixed

**Review by Arqu — APPROVED** [review]
🚀
