### PR TITLE
fix: avoid blockage in endpoint handling

### LINKED ISSUE #1568: test: sync_subscribe times out
Running this test on current `main` fails on my machine (macos) reliably

```
     Running tests/sync.rs (target/debug/deps/sync-6ea38533d3f95595)

running 2 tests
test sync_subscribe ... FAILED
test sync_subscribe_stop ... ok

failures:

---- sync_subscribe stdout ----
Error: deadline has elapsed


failures:
    sync_subscribe

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 6.20
```

### PR DESCRIPTION
**Pull request by dignifiedquire**
- avoid using `tokio::sync::watch` has it has a history of causing random blockages
- do not recursively call into the magicsocket to retrieve endpoints

Closes #1568

### CODE REVIEW

File: iroh-gossip/src/net.rs [hunk 1]
```diff
@@ -229,10 +231,14 @@ impl Gossip {
     ///
     /// This will be sent to peers on Neighbor and Join requests so that they can connect directly
     /// to us.
+    ///
+    /// This is only best effort, and will drop new events if backed up.
```
Comment (Frando) [inline iroh-gossip/src/net.rs:235]: That's why I opted for `Watch` in the first place: We only ever care for the latest value that was sent. Isn't there another alternative to `Watch` that keeps that behavior? Could just be something like a ringbuf with capacity 1.
But also fine to keep as is for now, there won't be more than 64 endpoint updates before the actor pulls them out.

**Review by Frando — APPROVED** [review]

File: iroh-gossip/src/net.rs (hunk 1 above)
Comment (dignifiedquire) [reply iroh-gossip/src/net.rs:235]: I don't trust watch.. I also looked at the tokio issue tracker and there are way too many cases where subtle misuse of it results in deadlocks
