### PR TITLE
fix: actually allow to disable DERP

### LINKED ISSUE #1558: Bug: `node::Builder::disable_derp` is broken
.. as in, has  no effect. We moved the default in `MagicEndpoint` to be the default derp map (and not no derp). However, we never call `MagicEndpointBuilder::disable_derp()`, even if you call `node::Builder::disable_derp`. This needs to be fixed.

### PR DESCRIPTION
**Pull request by Frando**
## Description

`node::Builder::disable_derp` is broken. We do not call `MagicEndpointBuilder::disable_derp` for that, and at some point we changed the magic endpoint to default to the default, n0-supplied derp servers.

This fixes this through a `DerpMode` enum that is much more explicit I think.

Fixes #1558 

## Change checklist

- [x] Self-review.
- [x] Documentation updates if relevant.
- [x] Tests if relevant.

### CODE REVIEW

File: iroh-net/src/magic_endpoint.rs [hunk 1]
```diff
@@ -253,13 +240,14 @@ impl MagicEndpointBuilder {
...
     pub async fn bind(self, bind_port: u16) -> Result<MagicEndpoint> {
-        ensure!(
-            self.derp_map
-                .as_ref()
-                .map(|m| !m.is_empty())
-                .unwrap_or(true),
-            "Derp server enabled but DerpMap is empty",
-        );
+        let derp_map = match self.derp_mode {
+            DerpMode::Disabled => DerpMap::default(),
```
Comment (dignifiedquire) [inline iroh-net/src/magic_endpoint.rs:244]: can we make sth like `DerpMap::empty()` or sth like that for this? `default` reads very confusing here

File: iroh/examples/sync.rs [hunk 2]
```diff
@@ -130,13 +132,14 @@ async fn run(args: Args) -> anyhow::Result<()> {
     println!("> our secret key: {}", secret_key);
 
     // configure our derp map
-    let derp_map = match (args.no_derp, args.derp) {
-        (false, None) => Some(default_derp_map()),
-        (false, Some(url)) => Some(DerpMap::from_url(url, 0)),
-        (true, None) => None,
+    // configure our derp map
```
Comment (flub) [inline iroh/examples/sync.rs:135]: dup comment

**Review by flub — APPROVED** [review]
agreed on `DerpMap::emtpy()`, that's been confusing for a while.  but overall this i much better than what i did before!

File: iroh-net/src/magic_endpoint.rs (hunk 1 above)
Comment (Frando) [reply iroh-net/src/magic_endpoint.rs]: fixed

File: iroh/examples/sync.rs (hunk 2 above)
Comment (Frando) [reply iroh/examples/sync.rs]: fixed
