### PR TITLE
fix(iroh)!: Don't publish IP addresses from `PkarrPublisher` by default

### LINKED ISSUE #4009: Accidental publishing of IP addresses in DNS
On current main we are accidentally publishing IP addresses into the pkarr/DNS address lookup service. We should not publish those by default, it should be a very explicit user action to publish those. By default only after connecting to a peer should IP addresses be exchanged between two peers, over the encrypted QUIC connection.

### PR DESCRIPTION
**Pull request by matheus23**
## Description

Partially reverts #3987 so we have more control over the default `AddrFilter` from within the `PkarrPublisherBuilder`, and because we need it for pkarr, we keep this consistent across publishing services.

As a bonus, now pure resolvers don't suddently have a builder method for address filtering that cannot apply to them (but they can still be wrapped in `FilteredAddressLookup`, even though that's less discoverable).

Fixes #4009 

## Breaking Changes

- **behavioral**: `PkarrPublisher` and `DhtPublisher` will now by default publish *only* the relay URL, instead of detecting if `RelayMode::Disabled` was set and in such cases publishing IP addresses. We recommend users to explicitly set `.addr_mode(AddrFilter::unfiltered())` if they set `relay_mode(RelayMode::Disabled)`, to re-enable publishing IP addresses publicly.

### CODE REVIEW

File: iroh/src/address_lookup/pkarr/dht.rs [hunk 1]
```diff
@@ -198,8 +192,29 @@ impl Builder {
...
+    /// even bypass a relay connection entirely.
+    pub fn addr_filter(mut self, filter: AddrFilter) -> Self {
+        self.addr_filter = filter;
+        self
+    }
+
     /// Builds the address lookup mechanism.
-    pub fn build(self) -> Result<DhtAddressLookup, AddressLookupBuilderError> {
+    ///
+    /// `relays_enabled` determines the default address filter when none was set via
```
Comment (Frando) [inline iroh/src/address_lookup/pkarr/dht.rs]: remove, outdated.

File: iroh-relay/src/endpoint_info.rs [hunk 2]
```diff
@@ -254,6 +254,11 @@ impl AddrFilter {
         Self(Some(Arc::new(f)))
     }
 
+    /// Constructs a filter that doesn't filter addresses and passes all through.
+    pub fn unfiltered() -> Self {
+        Self::new(|addrs| addrs.iter().cloned().collect())
```
Comment (dignifiedquire) [inline iroh-relay/src/endpoint_info.rs:259]: do all filters have to allocate? 😭 f

Comment (matheus23) [reply iroh-relay/src/endpoint_info.rs:259]: I had *just* the branch sitting on my hard drive for you: https://github.com/n0-computer/iroh/pull/4018

Comment (matheus23) [reply iroh-relay/src/endpoint_info.rs:259]: But do note the discussion section in that PR.

**Comment by dignifiedquire** [comment]
the mdns example might need some updates

File: iroh/src/address_lookup/pkarr/dht.rs [hunk 3]
```diff
@@ -42,25 +42,17 @@ const REPUBLISH_DELAY: Duration = Duration::from_secs(60 * 60);
 /// be used as both a publisher and resolver.  Calling [`DhtAddressLookup::publish`] will start
 /// a background task that periodically publishes the endpoint address.
 ///
-/// By default, [`DhtAddressLookup`] will publish all addresses it receives:
-/// direct IP addresses and relay URLs. No internal address limits or truncation
-/// are applied.
-///
-/// You can supply an [`AddrFilter`] via [`AddrLookupBuilder::with_addr_filter`] to
-/// control which addresses are published.
+/// [`DhtAddressLookup`] filters published addresses based on the endpoint's relay
```
Comment (Frando) [inline iroh/src/address_lookup/pkarr/dht.rs]: comment is wrong now, it's always relay_only unless set differently by the user, right?

File: iroh/src/address_lookup/pkarr.rs [hunk 4]
```diff
@@ -19,14 +19,11 @@
...
 //!
-//! [`PkarrPublisher`] publishes all addresses it receives by default, with no internal limiting.
-//! You can supply an [`AddrFilter`] via [`AddrLookupBuilder::with_addr_filter`] to limit the kinds
-//! and number of addresses that get published. When the [`PkarrPublisher`] is added via the
-//! [`N0` preset], a filter to publish only relay addresses is applied. If you add the publisher
-//! directly to an endpoint, you might want to do the same to not leak IP addresses publicly.
-//!
-//! Note that [`PkarrResolver`] and [`address_lookup::DnsAddressLookup`] only resolve and do not publish,
-//! so filtering does not apply to them.
+//! [`PkarrPublisher`] filters published addresses based on the endpoint's relay configuration
```
Comment (Frando) [inline iroh/src/address_lookup/pkarr.rs]: comment is wrong now, it's always relay_only unless set differently by the user, right?

File: iroh/src/address_lookup/pkarr.rs [hunk 5]
```diff
@@ -214,6 +215,20 @@ impl PkarrPublisherBuilder {
...
     }
 
+    /// Sets the address filter to control which addresses are published to the pkarr server.
+    ///
+    /// By default [`AddrFilter::relay_only`] is used. This avoids leaking IP addresses to the
+    /// public pkarr server.
+    ///
+    /// However, enabling IP address publishing can be useful, e.g. when iroh runs on a machine
+    /// connected to the internet via public IP addresses without a firewall.
+    /// In such cases, publishing them can make dialing such endpoints via DNS or PKARR lookup
```
Comment (Frando) [inline iroh/src/address_lookup/pkarr.rs]: nit: I think we usually write `Pkarr` not `PKARR`

**Comment by matheus23** [comment]
> the mdns example might need some updates

Does it? It seems to be working fine for me.

**Comment by dignifiedquire** [comment]
> > the mdns example might need some updates
> 
> Does it? It seems to be working fine for me.

it does, but we don't need to remove filters anymore, we could keep using the preset now

**Comment by matheus23** [comment]
Updated the example. This should be ready.
