### PR TITLE
fix: pass links to store when adding data

### LINKED ISSUE #287: Make sure links get persisted in the database
Currently, links are not being persisted in the store. Even when adding an object like an unixfs branch node, there are 0 links being passed via RPC.

Make sure links are properly passed via RPC so the store has the information it needs to traverse the DAG for caching/gc.

### PR DESCRIPTION
**Pull request by rklaehn**
Note that this may lead to decreased performance, since we are doing more work than before. But the store needs this information.

The way links are parsed can be optimized, see #297 . And I am not quite sure if finding links should not be done on the store side. But that is another discussion to be had.

Fixes #287

### CODE REVIEW

File: iroh-resolver/src/unixfs_builder.rs [hunk 1]
```diff
@@ -458,7 +459,8 @@ pub async fn add_file<S: Store>(store: Option<S>, path: &Path, wrap: bool) -> Re
     while let Some(part) = parts.next().await {
         let (cid, bytes) = part?;
         if let Some(ref store) = store {
-            store.put(cid, bytes, vec![]).await?;
+            let links = parse_links(&cid, &bytes)?;
+            store.put(cid, bytes, links).await?;
```
Comment (dignifiedquire) [inline iroh-resolver/src/unixfs_builder.rs:463]: we already know the links, when we encode things. instead of parsing them out, we should expose them from the underlying generator and use them here

Comment (rklaehn) [reply iroh-resolver/src/unixfs_builder.rs:463]: OK

Comment (rklaehn) [reply iroh-resolver/src/unixfs_builder.rs:463]: Digging into this now. This will be a bit of a bigger operation then... Got lots of places where the links need to be funneled though....

**Comment by rklaehn** [comment]
I am now passing through all the links, so at all places where there was a (Cid, Bytes) before there is a (Cid, Bytes, Vec<Cid>> now. But I don't like it very much. It is a bit verbose and error prone. So will try making a struct and see how that goes...

File: iroh-resolver/src/unixfs_builder.rs [hunk 2]
```diff
@@ -671,14 +672,20 @@ mod tests {
...
     ) -> Result<(Cid, Resolver<Arc<fnv::FnvHashMap<Cid, Bytes>>>)> {
         tokio::pin!(stream);
         let items: Vec<_> = stream.try_collect().await?;
-        let (root, _) = items.last().context("no root")?.clone();
-        let store: fnv::FnvHashMap<Cid, Bytes> = items.into_iter().collect();
+        let root_block = items.last().context("no root")?.clone();
+        let store: fnv::FnvHashMap<Cid, Bytes> = items
+            .into_iter()
+            .map(|block| {
+                let (cid, bytes, _) = block.into_parts();
```
Comment (dignifiedquire) [inline iroh-resolver/src/unixfs_builder.rs:683]: Probably should have a test that checks that the links are actually stored in the store

Comment (rklaehn) [reply iroh-resolver/src/unixfs_builder.rs:683]: Will do. Just want to see how I like the Block struct. I think it is good...

**Comment by dignifiedquire** [comment]
Lets get this in and make a new issue for adding adding tests

**Review by dignifiedquire — DISMISSED** [review]

**Comment by rklaehn** [comment]
Made a followup issue for the proposed tests: #315

**Review by dignifiedquire — APPROVED** [review]
nice catch
