### PR TITLE
fix(iroh): handle out of bounds requests for blobs read_at

### LINKED ISSUE #2728: Panic if a chunk with out-of-bounds offset is requested.
Upon a call to `iroh_client.blobs().read_at_to_bytes` with out-of-bounds offset, it panics. 
It would be more convenient to return `Err` so that we don't need to check bounds upfront.

Stacktrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:180:21
   3: iroh::node::rpc::Handler<D>::blob_read_at::read_loop::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iroh-0.22.0/src/node/rpc.rs:1023:41
   4: iroh::node::rpc::Handler<D>::blob_read_at::{{closure}}::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iroh-0.22.0/src/node/rpc.rs:1002:87
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   6: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
   7: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
   8: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
   9: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  11: std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  12: ___rust_try
  13: std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  14: std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  15: tokio::runtime::task::harness::poll_future
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
  16: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
  17: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
  18: tokio::runtime::task::raw::poll
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
  19: tokio::runtime::task::raw::RawTask::poll
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
  20: tokio::runtime::task::LocalNotified<S>::run
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:427:9
  21: tokio::task::local::LocalSet::tick::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:693:63
  22: tokio::runtime::coop::with_budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  23: tokio::runtime::coop::budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  24: tokio::task::local::LocalSet::tick
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:693:31
  25: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:999:16
  26: tokio::task::local::LocalSet::with::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:747:13
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:286:12
  28: std::thread::local::LocalKey<T>::with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:9
  29: tokio::task::local::LocalSet::with
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:745:9
  30: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:985:9
  31: tokio::task::local::LocalSet::run_until::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/task/local.rs:639:19
  32: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:63
  33: tokio::runtime::coop::with_budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  34: tokio::runtime::coop::budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  35: tokio::runtime::park::CachedParkThread::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:31
  36: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/blocking.rs:66:9
  37: tokio::runtime::handle::Handle::block_on_inner::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/handle.rs:324:13
  38: tokio::runtime::context::runtime::enter_runtime
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  39: tokio::runtime::handle::Handle::block_on_inner
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/handle.rs:323:9
  40: tokio::runtime::handle::Handle::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/handle.rs:302:13
  41: iroh_blobs::util::local_pool::LocalPool::spawn_pool_thread::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iroh-blobs-0.22.0/src/util/local_pool.rs:189:37
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'iroh::tests::test_download_chunk_out_of_bounds' panicked at storage/src/iroh.rs:313:9:
assertion failed: result.is_err()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
   3: storage::iroh::tests::test_download_chunk_out_of_bounds::{{closure}}
             at ./src/iroh.rs:313:9
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:673:57
   7: tokio::runtime::coop::with_budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:673:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:412:19
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:672:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:751:68
  13: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
  14: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:26
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:286:12
  16: std::thread::local::LocalKey<T>::with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:9
  17: tokio::runtime::context::set_scheduler
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:751:27
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:660:19
  20: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:180:28
  21: tokio::runtime::context::runtime::enter_runtime
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/current_thread/mod.rs:168:9
  23: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:361:47
  24: tokio::runtime::runtime::Runtime::block_on
             at /Users/islam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:335:13
  25: storage::iroh::tests::test_download_chunk_out_of_bounds
             at ./src/iroh.rs:318:9
  26: storage::iroh::tests::test_download_chunk_out_of_bounds::{{closure}}
             at ./src/iroh.rs:307:53
  27: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #2728

### CODE REVIEW

File: iroh/src/node/rpc.rs [hunk 1]
```diff
@@ -1230,15 +1230,33 @@ impl<D: BaoStore> Handler<D> {
...
+                anyhow::bail!(
+                    "requested offset is out of range: {} > {:?}",
+                    req.offset,
+                    size
+                );
+            }
+
+            let len = req.len.unwrap_or((size.value() - req.offset) as usize);
+
+            if req.offset + len as u64 > size.value() {
```
Comment (rklaehn) [inline iroh/src/node/rpc.rs:1244]: You could also use anyhow::ensure for these two.

**Review by rklaehn — APPROVED** [review]
