### PR TITLE
fix tls bugs & create an `hp::derp::http::server::Server`

### LINKED ISSUE #908: TLS Support in Derp

### PR DESCRIPTION
**Pull request by ramfox**
The derper & our tests now use a `hp::derp::http::server::Server` as a Http(s) derp server.

PR also fixes bugs in the tls connection.

closes #908

### CODE REVIEW

File: src/hp/derp/client_conn.rs [hunk 1]
```diff
@@ -118,60 +115,52 @@ impl ClientConnManager {
...
-        let writer_handle = tokio::spawn(async move {
-            let key = writer_client_id.0;
-            let conn_num = writer_client_id.1;
-            let res = conn_writer.run(writer_done).await;
-            let _ = writer_server_channel
+        // start io loop
+        let io_done = done.clone();
+        let io_client_id = client_id.clone();
+        let io_server_channel = server_channel.clone();
+        let io_handle = tokio::task::spawn(async move {
```
Comment (flub) [inline src/hp/derp/client_conn.rs:159]: you have some `trace!` calls in `conn_io.run()`, would be great to attach `.instrument(tracing::debug_span!("conn_io"))` or similar to this async block as that would give nice context for those.  Like at https://github.com/n0-computer/iroh/blob/6df66f479aac274f8231aaabbe3d11f07521b6a4/src/hp/netcheck.rs#LL1702C21-L1702C21

File: src/hp/derp/client_conn.rs [hunk 2]
```diff
@@ -747,44 +688,130 @@ mod tests {
...
-    async fn test_client_conn_reader_basic() -> Result<()> {
-        let (reader, mut writer) = tokio::io::duplex(1024);
-        let (send_pong_s, mut send_pong_r) = mpsc::channel(10);
-        let (server_channel_s, mut server_channel_r) = mpsc::channel(10);
+    async fn test_client_conn_io_basic() -> Result<()> {
+        tracing_subscriber::registry()
+            .with(tracing_subscriber::fmt::layer().with_writer(std::io::stderr))
+            .with(EnvFilter::from_default_env())
+            .try_init()
+            .ok();
```
Comment (flub) [inline src/hp/derp/client_conn.rs:696]: could i nudge you to try out https://github.com/n0-computer/iroh/blob/6df66f479aac274f8231aaabbe3d11f07521b6a4/src/test_utils.rs#L16 ?  It seems there might still be a bug with it so if it blows up for you stick with this.  But otherwise it brings some benefits.

File: src/hp/derp/http/server.rs [hunk 3]
```diff
@@ -1,50 +1,404 @@
...
+            tls_config: self.tls_config,
+            server: derp_server,
+            service,
+        };
+
+        server_state.serve().await
+    }
+}
+
+impl std::fmt::Debug for ServerBuilder {
```
Comment (flub) [inline src/hp/derp/http/server.rs:264]: I think dig went on a quest to remove the manual debug impls and introduced `derive_more::Debug`.  e.g. https://github.com/n0-computer/iroh/blob/6df66f479aac274f8231aaabbe3d11f07521b6a4/src/hp/magicsock/endpoint.rs#L80

File: src/hp/derp/http/server.rs [hunk 4]
```diff
@@ -1,50 +1,404 @@
...
+
+    /// Binds a TCP listener on `addr` and handles content using HTTP.
+    /// Returns the local `SocketAddr` on which the server is listening.
+    async fn http_serve(self) -> Result<Server> {
+        let http_listener = TcpListener::bind(&self.addr)
+            .await
+            .context("failed to bind https")?;
+        let addr = http_listener.local_addr()?;
+        let cancel = CancellationToken::new();
+        info!("[HTTP] derp: serving on {addr}");
```
Comment (flub) [inline src/hp/derp/http/server.rs:308]: If you'd like to be fancier you can like do `self.http_serve().instrument(debug_span!("derp_http")).await` on line 296 and then use `info!(%addr, "serving");` here.

File: src/hp/derp/http/server.rs [hunk 5]
```diff
@@ -1,50 +1,404 @@
...
+        let c = cancel.clone();
+        let task = tokio::task::spawn(async move {
+            debug!("about to loop");
+            loop {
+                match http_listener.accept().await {
+                    Ok((stream, peer_addr)) => {
+                        debug!("[HTTP] derp: Connection opened from {}", peer_addr);
+                        let service = self.service.clone();
+                        let cancel = c.clone();
+                        tokio::task::spawn(async move {
```
Comment (flub) [inline src/hp/derp/http/server.rs:318]: should probably instrument this spawned future with a span?

File: src/hp/derp/http/server.rs [hunk 6]
```diff
@@ -1,50 +1,404 @@
...
+            .await
+            .context("failed to bind https")?;
+        let addr = http_listener.local_addr()?;
+        let cancel = CancellationToken::new();
+        info!("[HTTP] derp: serving on {addr}");
+        let c = cancel.clone();
+        let task = tokio::task::spawn(async move {
+            debug!("about to loop");
+            loop {
+                match http_listener.accept().await {
```
Comment (flub) [inline src/hp/derp/http/server.rs:313]: Does this loop terminate when the cancel token in cancelled?

File: src/hp/derp/http/server.rs [hunk 7]
```diff
@@ -109,145 +463,199 @@ where
...
+        }
+        // otherwise return 404
+        let res = (self.0.not_found_fn)(self.0.default_response());
+        Box::pin(async move { res })
+    }
+}
 
-        let (mut request_sender, connection) =
-            hyper::client::conn::handshake(tcp_stream).await.unwrap();
+#[derive(Clone)]
```
Comment (flub) [inline src/hp/derp/http/server.rs:506]: no `Debug`?

File: src/hp/derp/http/server.rs [hunk 8]
```diff
@@ -109,145 +463,199 @@ where
...
-            let _ = connection.without_shutdown().await;
-        });
+type HyperFn = Box<dyn Fn(ResponseBuilder) -> HyperResult<Response<Body>> + Send + Sync + 'static>;
+type Headers = Vec<(&'static str, &'static str)>;
 
-        let req = Request::builder()
-            .header(UPGRADE, super::HTTP_UPGRADE_PROTOCOL)
-            .body(Body::empty())
-            .unwrap();
+struct Inner {
```
Comment (flub) [inline src/hp/derp/http/server.rs:513]: derive `Debug` somehow (with derive_more if needed)

File: src/hp/derp/http/server.rs [hunk 9]
```diff
@@ -109,145 +463,199 @@ where
...
+    /// Pass the connection to a ClientConnHandler to get added to the derp server. The default.
+    ConnHandler(ClientConnHandler<crate::hp::derp::http::Client>),
+    /// Return some static response. Used when the http(s) should be running, but the derp portion
+    /// of the server is disabled.
+    Override(HyperFn),
+}
 
-        if res.status() != StatusCode::SWITCHING_PROTOCOLS {
-            panic!("Our server didn't upgrade: {}", res.status());
+impl std::fmt::Debug for DerpHandler {
```
Comment (flub) [inline src/hp/derp/http/server.rs:530]: derive_more?

File: src/hp/derp/http/server.rs [hunk 10]
```diff
@@ -109,145 +463,199 @@ where
...
+    LetsEncrypt(AcmeAcceptor),
+    /// Manually added tls acceptor. Generally used for tests or for when we've passed in
+    /// a certificate via a file.
+    Manual(tokio_rustls::TlsAcceptor),
+}
 
-    impl PacketForwarder for MockPacketForwarder {
-        fn forward_packet(&mut self, srckey: PublicKey, dstkey: PublicKey, packet: bytes::Bytes) {
-            println!("forwarded packet from {srckey:?} to {dstkey:?}: msg: {packet:?}");
+impl std::fmt::Debug for TlsAcceptor {
```
Comment (flub) [inline src/hp/derp/http/server.rs:565]: derive_more?

File: src/hp/derp/http/server.rs [hunk 11]
```diff
@@ -109,145 +463,199 @@ where
...
-                                .with_upgrades()
-                                .await
-                            {
-                                eprintln!("Failed to serve connection: {:?}", err);
-                            }
-                        });
-                    }
-                }
-            }
+impl std::fmt::Debug for Handlers {
```
Comment (flub) [inline src/hp/derp/http/server.rs:634]: derive_more?

File: src/hp/dns.rs [hunk 12]
```diff
@@ -0,0 +1,19 @@
+use trust_dns_resolver::TokioAsyncResolver;
+
+use once_cell::sync::Lazy;
+pub static DNS_RESOLVER: Lazy<TokioAsyncResolver> = Lazy::new(|| {
+    TokioAsyncResolver::tokio_from_system_conf().expect("unable to create DNS resolver")
+});
```
Comment (flub) [inline src/hp/dns.rs:6]: ooh, nice i think.

(though the blank lines are a bit wonky)

File: src/bin/derper.rs [hunk 13]
```diff
@@ -60,6 +58,19 @@ struct Cli {
...
+    /// only use `ECDSA` keys. In their current set up, you can only get intermediate certificates
+    /// for `ECDSA` keys if you are on their "allowlist". The production server uses `RSA` keys,
+    /// which allow for issuing intermediate certificates in all normal circumstances.
+    /// So, to have valid certificates, we must use the LetsEncrypt production server.
+    /// Read more here: <https://letsencrypt.org/certificates/#intermediate-certificates>
+    /// Default is true. This flag is ignored if we are not using `cert_mode: CertMode::LetsEncrypt`.
+    #[clap(long, default_value_t = true)]
+    prod_tls: bool,
+    /// The contact email for the tls certificate
+    #[clap(long, default_value = "d@n0.computer")]
```
[the remark this answers is not in the document]
Comment (ramfox) [reply src/bin/derper.rs:70]: removed the default & added an error if this is not supplied when running the Derper with TLS enabled

File: src/bin/derper.rs [hunk 14]
```diff
@@ -369,94 +397,27 @@ const TLS_HEADERS: [(&str, &str); 2] = [
...
-        }
-
-        let http_addr = SocketAddr::new(addr.ip(), http_port);
-        let http_listener = TcpListener::bind(&http_addr)
-            .await
-            .context("failed to bind http")?;
-        let http_addr = http_listener.local_addr()?;
-        info!("[HTTP] derper: serving on {}", http_addr);
+async fn serve_http(addr: SocketAddr, http_port: u16) -> Result<tokio::task::JoinHandle<()>> {
+    let http_addr = SocketAddr::new(addr.ip(), http_port);
```
[the remark this answers is not in the document]
Comment (ramfox) [reply src/bin/derper.rs:399]: adjusted!

File: src/hp/derp/http/server.rs (hunk 11 above)
Comment (ramfox) [reply src/hp/derp/http/server.rs:634]: Okay, this was the only one I couldn't figure out how to bend to my will using `derive_more`

File: src/hp/dns.rs (hunk 12 above)
Comment (ramfox) [reply src/hp/dns.rs:6]: this file is all dig! fixing the formatting tho

File: src/hp/derp/http/server.rs (hunk 6 above)
Comment (ramfox) [reply src/hp/derp/http/server.rs:313]: I was handling shutdown in a strange way and this comment nudged me to do better, so thank you! 

Now, when we call `server.shutdown()`:
- We use the cancel token to close the loop in the task that listens for incoming connections (called this `http_server_task`)
- Each incoming connection caused a new task to be spawned on a `JoinSet`. That `JoinSet` is cleaned up in the `http_server_task` task when the loop is closed. 
- Then we wait for the `http_server_task` to finish, and log any errors that occur when attempting to shut it down.

I think this is much cleaner, however, it still feels a bit roundabout. Suggestions welcome.

File: src/hp/derp/client_conn.rs (hunk 2 above)
Comment (ramfox) [reply src/hp/derp/client_conn.rs:696]: what's the latest status on this? Having trouble grasping it based on the latest discord convo on logging.

File: src/hp/derp/http/server.rs (hunk 5 above)
Comment (ramfox) [reply src/hp/derp/http/server.rs:318]: Can I get a double check that I executed this correctly?

File: src/hp/derp/client_conn.rs (hunk 2 above)
Comment (flub) [reply src/hp/derp/client_conn.rs:699]: since this test uses a single-threaded tokio runtime it Should Just Work (tm) with `crate::test_utils::setup_logging`.  it's the multi-threaded runtimes that are still struggling.

File: src/hp/derp/http/server.rs (hunk 6 above)
Comment (flub) [reply src/hp/derp/http/server.rs]: seems very reasonable and easy to follow.  i wouldn't say roundabout

File: src/hp/derp/http/server.rs (hunk 5 above)
Comment (flub) [reply src/hp/derp/http/server.rs]: looks good

File: src/bin/derper.rs [hunk 15]
```diff
@@ -322,7 +322,8 @@ async fn main() -> Result<()> {
     };
 
     let tls_config = if serve_tls {
-        let contact = cli.tls_contact;
+        // checked earlier
+        let contact = cli.tls_contact.unwrap();
```
Comment (flub) [inline src/bin/derper.rs:326]: `.expect("checked earlier")` is probably a tiny bit more idiomatic

**Review by flub — APPROVED** [review]

File: src/hp/derp/http/server.rs [hunk 16]
```diff
@@ -1,50 +1,334 @@
...
-        parts.read_buf
+        read_buf
     );
 
-    // split into the reader and writer parts
-    let (reader, writer) = parts.io.into_split();
+    conn_handler.accept(io).await
+}
+
+#[derive(Debug)]
```
Comment (flub) [inline src/hp/derp/http/server.rs:68]: odd place to put the derive ;)

**Review by flub — APPROVED** [review]

File: src/hp/derp/http/server.rs (hunk 16 above)
Comment (ramfox) [reply src/hp/derp/http/server.rs:68]: what you don't like it dangling around in the wind like that 😄 ?

**Review by Arqu — APPROVED** [review]
🐰

File: src/config.rs [hunk 17]
```diff
@@ -101,12 +101,12 @@ fn default_derp_region() -> DerpRegion {
     let default_n0_derp = DerpNode {
         name: "default-1".into(),
         region_id: 1,
-        host_name: "derp.iroh.computer".into(),
+        host_name: "derp.iroh.network".into(),
         stun_only: false,
         stun_port: 3478,
-        ipv4: UseIpv4::Some("35.175.99.113".parse().unwrap()),
+        ipv4: UseIpv4::Some("174.129.122.106".parse().unwrap()),
```
Comment (Arqu) [inline src/config.rs:107]: the IP should remain the same (the IP here is of the dev-derper box)

**Review by Arqu — CHANGES_REQUESTED** [review]

**Review by Arqu — APPROVED** [review]
🐰 🐰
