### PR TITLE
fix(iroh-blobs): unconditionally delete blobs

### LINKED ISSUE #2657: in some (most) cases `blobs delete blob <hash>` seems to do nothing
Using main at [c70caaf](https://github.com/n0-computer/iroh/commit/c70caaf48ac39fcfb3b971366a76bff37b493ee9)

I think I have seen this work once, but in most cases It looks like it isn't doing anything.

### Reproduction steps
1. start iroh
  ```fish
  env IROH_DATA_DIR=/tmp/fresh_dir iroh start
  ```
2. start the console somewhere else
  ```fish
  env IROH_DATA_DIR=/tmp/fresh_dir iroh console
  ```
3. add a blob
  ```fish
  > blobs list blobs # empty, dir is fresh
  > blobs add CONTRIBUTING.md
  Adding CONTRIBUTING.md as /home/divagant-martian/Workspace/iroh/CONTRIBUTING.md...
  - /home/divagant-martian/Workspace/iroh/CONTRIBUTING.md: 5.20 KiB pnzfqspcskqur4kuwck7hc7yxkkm4exuhle5urbssozi3zttjdjq
Total: 5.20 KiB

Blob: pnzfqspcskqur4kuwck7hc7yxkkm4exuhle5urbssozi3zttjdjq
All-in-one ticket: blobacm6x2wx23oc2ssbxqubxlaa2jeptmvbjbjewygviwqx3usz3f47oaiqnb2hi4dthixs6ztpn4xgeylsf4babqfiaah4ivyazhmaaauk4abaa63slbe6fevbjdyvjmev6of7rouuzyjpiowj3jcdfe5srxthgsgt
> blobs list blobs
 pnzfqspcskqur4kuwck7hc7yxkkm4exuhle5urbssozi3zttjdjq (5.20 KiB)
  ```
5. "delete" the blob
```fish
> blobs delete blob pnzfqspcskqur4kuwck7hc7yxkkm4exuhle5urbssozi3zttjdjq
# empty response, so it's assumed all worked
> blobs list blobs
 pnzfqspcskqur4kuwck7hc7yxkkm4exuhle5urbssozi3zttjdjq (5.20 KiB)
# wut face
```

### PR DESCRIPTION
**Pull request by dignifiedquire**
- always delete hashes, even if they are protected when calling `Store::delete`
- move gc loop implementation into the stores

## Breaking Changes

- removed `Store::gc_sweep`
- removed `Store::gc_mark`
- removed `Store::gc_start`
- added `Store::gc_run` which starts the full gc schedule

Closes #2657

### CODE REVIEW

**Review by rklaehn — COMMENTED** [review]
Not a big fan of multiple callbacks that return futures. But then again this wasn't exactly beautiful before either...

File: iroh-blobs/src/store/fs.rs [hunk 1]
```diff
@@ -627,6 +630,11 @@ pub(crate) enum ActorMessage {
         hashes: Vec<Hash>,
         tx: oneshot::Sender<ActorResult<()>>,
     },
+    /// Modification method: try to delete the data for a number of hashes
```
Comment (rklaehn) [inline iroh-blobs/src/store/fs.rs:633]: This docs should probably say that GcDelete is not "force delete".

File: iroh-blobs/src/store/fs.rs [hunk 2]
```diff
@@ -2253,7 +2371,11 @@ impl ActorState {
                 tx.send(res).ok();
             }
             ActorMessage::Delete { hashes, tx } => {
```
Comment (rklaehn) [inline iroh-blobs/src/store/fs.rs:2373]: I would have just added the force flag to the Delete message, but this works as well...

**Review by rklaehn — APPROVED** [review]
Not a big fan of multiple callbacks that return futures. But then again this wasn't exactly beautiful before either...
