### PR TITLE
fix(netcheck): Build test ProbePlan from fake interface data

### LINKED ISSUE #1263: Test test_plan_with_report consistently fails on my home network
Test output:

```
thread 'hp::netcheck::reportgen::probes::tests::test_plan_with_report' panicked at 'assertion failed: `(left == right)`: 0

Diff < left / right > :
 ProbePlan(
     {
         ProbeSet {
             name: "region-1-https",
             proto: Https,
             probes: [
                 Https {
                     delay: 207.2ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 1,
                         nodes: [
                             DerpNode {
                                 name: "na-default-1",
                                 region_id: 1,
                                 url: https://derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     35.175.99.113,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-1",
                     },
                 },
                 Https {
                     delay: 259.6ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 1,
                         nodes: [
                             DerpNode {
                                 name: "na-default-1",
                                 region_id: 1,
                                 url: https://derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     35.175.99.113,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-1",
                     },
                 },
                 Https {
                     delay: 312ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 1,
                         nodes: [
                             DerpNode {
                                 name: "na-default-1",
                                 region_id: 1,
                                 url: https://derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     35.175.99.113,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-1",
                     },
                 },
                 Https {
                     delay: 364.4ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 1,
                         nodes: [
                             DerpNode {
                                 name: "na-default-1",
                                 region_id: 1,
                                 url: https://derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     35.175.99.113,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-1",
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-1-icmp",
             proto: Icmp,
             probes: [
                 Icmp {
                     delay: 207.2ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 Icmp {
                     delay: 259.6ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 Icmp {
                     delay: 312ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 Icmp {
                     delay: 364.4ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-1-stunipv4",
             proto: StunIpv4,
             probes: [
                 StunIpv4 {
                     delay: 0ns,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv4 {
                     delay: 52.4ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv4 {
                     delay: 104.8ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv4 {
                     delay: 157.2ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-1-stunipv6",
             proto: StunIpv6,
             probes: [
                 StunIpv6 {
                     delay: 0ns,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv6 {
                     delay: 52.4ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv6 {
                     delay: 104.8ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv6 {
                     delay: 157.2ms,
                     node: DerpNode {
                         name: "na-default-1",
                         region_id: 1,
                         url: https://derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             35.175.99.113,
                         ),
                         ipv6: TryDns,
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-2-https",
             proto: Https,
             probes: [
                 Https {
                     delay: 414.4ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 2,
                         nodes: [
                             DerpNode {
                                 name: "eu-default-1",
                                 region_id: 2,
                                 url: https://eu1.derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     52.30.229.248,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-2",
                     },
                 },
                 Https {
                     delay: 466.8ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                     region: DerpRegion {
                         region_id: 2,
                         nodes: [
                             DerpNode {
                                 name: "eu-default-1",
                                 region_id: 2,
                                 url: https://eu1.derp.iroh.network./,
                                 stun_only: false,
                                 stun_port: 3478,
                                 stun_test_ip: None,
                                 ipv4: Some(
                                     52.30.229.248,
                                 ),
                                 ipv6: TryDns,
                             },
                         ],
                         avoid: false,
                         region_code: "default-2",
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-2-icmp",
             proto: Icmp,
             probes: [
                 Icmp {
                     delay: 414.4ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 Icmp {
                     delay: 466.8ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-2-stunipv4",
             proto: StunIpv4,
             probes: [
                 StunIpv4 {
                     delay: 0ns,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv4 {
                     delay: 52.4ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
             ],
         },
         ProbeSet {
             name: "region-2-stunipv6",
             proto: StunIpv6,
             probes: [
                 StunIpv6 {
                     delay: 0ns,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
                 StunIpv6 {
                     delay: 52.4ms,
                     node: DerpNode {
                         name: "eu-default-1",
                         region_id: 2,
                         url: https://eu1.derp.iroh.network./,
                         stun_only: false,
                         stun_port: 3478,
                         stun_test_ip: None,
                         ipv4: Some(
                             52.30.229.248,
                         ),
                         ipv6: TryDns,
                     },
                 },
>                StunIpv6 {
>                    delay: 104.8ms,
>                    node: DerpNode {
>                        name: "eu-default-1",
>                        region_id: 2,
>                        url: https://eu1.derp.iroh.network./,
>                        stun_only: false,
>                        stun_port: 3478,
>                        stun_test_ip: None,
>                        ipv4: Some(
>                            52.30.229.248,
>                        ),
>                        ipv6: TryDns,
>                    },
>                },
>                StunIpv6 {
>                    delay: 157.2ms,
>                    node: DerpNode {
>                        name: "eu-default-1",
>                        region_id: 2,
>                        url: https://eu1.derp.iroh.network./,
>                        stun_only: false,
>                        stun_port: 3478,
>                        stun_test_ip: None,
>                        ipv4: Some(
>                            52.30.229.248,
>                        ),
>                        ipv6: TryDns,
>                    },
>                },
             ],
         },
     },
 )

', iroh-net/src/hp/netcheck/reportgen/probes.rs:883:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by flub**
## Description

The tests are supposed to be purely algorithmic, but they were reliant
on the local interfaces discovered which made them fickle.  This
spells out the interface which is much more reliable.

More variations in the interface states are probably useful too, but
for now this gives us some basic coverage of probe plans.

Closes #1263

## Change checklist

- [x] Self-review.
- [x] Documentation updates if relevant.
- [x] Tests if relevant.

### CODE REVIEW

File: iroh-net/src/net/interfaces.rs [hunk 1]
```diff
@@ -35,7 +35,7 @@ use self::windows::default_route;
 /// Represents a network interface.
 #[derive(Debug)]
 pub struct Interface {
-    iface: default_net::interface::Interface,
+    pub(crate) iface: default_net::interface::Interface,
```
Comment (dignifiedquire) [inline iroh-net/src/net/interfaces.rs:38]: Instead of exposing this, about exposing a test cfg'ed  `Interface::fake()`?

File: iroh-net/src/net/interfaces.rs [hunk 2]
```diff
@@ -70,6 +70,38 @@ impl Interface {
             .map(IpNet::V4)
             .chain(self.iface.ipv6.iter().cloned().map(IpNet::V6))
     }
+
+    #[cfg(test)]
+    pub(crate) fn fake() -> Self {
```
Comment (dignifiedquire) [inline iroh-net/src/net/interfaces.rs:75]: maybe add a doc comment for why this exists/what it is used for

Comment (flub) [reply iroh-net/src/net/interfaces.rs:84]: [2ad536b](https://github.com/n0-computer/iroh/pull/1266/commits/2ad536bffb87e34c9bd958d89d6b94fabec289aa)

**Review by dignifiedquire — APPROVED** [review]
